version: '2.4'
services:
  antizapret-vpn:
    image: alexunderboots/antizapret-vpn
    build: ./
    container_name: vpn-3nity
    restart: unless-stopped
    ports:
      - "443:997/tcp"
      - "7552:7552/tcp"
    volumes:
      - config:/etc/openvpn/server
      - ccd:/etc/openvpn/server/ccd
#      - logs:/etc/openvpn/server/logs
      - add:/root/antizapret/config/add
#    volumes:
#      - /mnt/ovpn:/etc/openvpn/server
#      - /mnt/general/ccd:/etc/openvpn/server/ccd
#      - ./config/ovpn/logs:/etc/openvpn/server/logs
#      - /mnt/add/include-hosts-custom.txt:/root/antizapret/config/add/include-hosts-custom.txt
    privileged: true
    logging:
      driver: "json-file"
      options:
        max-size: "100k"
        max-file: "1"
volumes:
  config:
    driver: local
    driver_opts:
      type: "nfs"
      o: "addr=10.110.0.15,nolock,rw,soft,nfsvers=4"
      device: ":/mnt/ovpn"
  ccd:
    driver: local
    driver_opts:
      type: "nfs"
      o: "addr=10.110.0.15,nolock,rw,soft,nfsvers=4"
      device: ":/mnt/general/ccd"
  add:
    driver: local
    driver_opts:
      type: "nfs"
      o: "addr=10.110.0.15,nolock,rw,soft,nfsvers=4"
      device: ":/mnt/add"
#  logs:
#    driver: local
#    driver_opts:
#      type: "nfs"
#      o: "addr=10.110.0.15,nolock,rw,soft,nfsvers=4"
#      device: ":/var/nfs/test/logs"
